### ISSUE TITLE
Effect of -DPROJECT_SOURCE_DIR?

### ISSUE THREAD

**Issue by DaanDeMeyer** [Polytonic/Glitter#27]
I was wondering what the effect was of adding the DPROJECT_SOURCE_DIR compile definition in CmakeLists.txt.

**Comment by Polytonic** [comment]
You may find the entries on [add_definitions](https://cmake.org/cmake/help/v3.5/command/add_definitions.html) and [PROJECT_SOURCE_DIR](https://cmake.org/cmake/help/v3.5/variable/PROJECT_SOURCE_DIR.html) to be of interest. 

In this specific case, `add_definitions(-DPROJECT_SOURCE_DIR=\"${PROJECT_SOURCE_DIR}\")` adds the project source directory as a preprocessor directive. 

Does that answer your question?

**Comment by DaanDeMeyer** [comment]
Thanks, but why is it necessary to do this?

**Comment by Polytonic** [comment]
It's not strictly mandatory, but can be helpful if you generate both makefiles and IDE project files and you need to perform file operations. The former uses just the project root, but the latter option can be problematic since different IDEs have different project layouts. Providing the project source directory as a preprocessor directive allows you to open files from a uniform directory, rather than mucking around with relative directories that may move depending on where your binary is generated.

**Comment by DaanDeMeyer** [comment]
Alright, thank you for taking the time to explain everything!
