### ISSUE TITLE
All files actually pushed?

### ISSUE THREAD

**Issue by shadowmint** [Polytonic/Glitter#7]
Is there some missing code in here?

Looks like nothing references the samples, and mesh.cpp refers to some Mirage/ folder, and CMakeLists.txt refers to Glitter/Shaders/ that doesn't exist.

If this is still a WIP, that's cool, just pointing out that at the moment the sample compiles to an empty grey screen that simply renders:

```
    // Rendering Loop
    while (glfwWindowShouldClose(mWindow) == false) {
        if (glfwGetKey(mWindow, GLFW_KEY_ESCAPE) == GLFW_PRESS)
            glfwSetWindowShouldClose(mWindow, true);

        // Background Fill Color
        glClearColor(0.25f, 0.25f, 0.25f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        // Flip Buffers and Draw
        glfwSwapBuffers(mWindow);
        glfwPollEvents();
    }
```

... not this, from the readme -> https://camo.githubusercontent.com/d9eb4d3e9cfe1f1a3f85fabf0cdf75d47975a07d/687474703a2f2f692e696d6775722e636f6d2f4d446f327273792e6a7067

**Comment by Polytonic** [comment]
I haven't decided what I want to do with them so it's a bit of a WIP.  I'm open to feedback though! Do you think people would find more complete implementations helpful?

Nothing references the samples, yes. They're mostly an afterthought, since I wrote this originally for a game architecture class. They are ripped directly from my OpenGL renderer. I put them there for people to follow if they get stuck when writing their own shader or mesh class. See [Documentation](https://github.com/Polytonic/Glitter#documentation)

>I have provided sample implementations of an intrusive tree mesh and shader class. These were used to generate the screenshot above, but will not compile out-of-the-box. I leave that exercise to the reader. :smiley:

Glitter/Shaders/ was an empty folder, was never committed. There's some degree of cleanup I have to do still, apparently.

**Comment by Polytonic** [comment]
@shadowmint just wanted to follow up on this. I added another readme to the samples directory, if that's more explanatory/helpful?

**Comment by shadowmint** [comment]
That clears things up I think~ :)
